import React from "react";

import { Geist, Geist_Mono } from "next/font/google";

import { AtlaskitThemeProvider } from "@/components/AtlaskitThemeProvider";

import '@atlaskit/css-reset';
import "./globals.css";

import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AtlaskitThemeProvider />
        {children}
      </body>
    </html>
  );
}
