import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { setGlobalTheme } from '@atlaskit/tokens';

import '@atlaskit/css-reset';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (typeof window !== 'undefined') {
    setGlobalTheme({
        light: 'light',
        dark: 'dark',
        colorMode: 'auto',
    }).finally(() => console.log('Global theme set.'));
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
